{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Setting up the environment:\n",
    "\n",
    "#### Using uv:\n",
    "!uv venv \"gemmatest\"\n",
    "\n",
    "#### Install ipykernel for using jypyternotes:\n",
    "!uv pip install ipykernel"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Now our environment \"gemmatest\" is setup.\n",
    "\n",
    "To start :\n",
    "\n",
    "gemmatest/Scripts/activate"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hello! Im being printed in the new env 'Gemmatest' \n"
     ]
    }
   ],
   "source": [
    "print(\"Hello! Im being printed in the new env 'Gemmatest' \")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Setting up Gemma\n",
    "\n",
    "!uv pip install gemma\n",
    "\n",
    "So some notes here, apparently the standard version of the \"pip install gemma\" doesnt work, so i would suggest using the \"pip install +repolink\" method- Also raised this issue in their github - https://github.com/google-deepmind/gemma/issues/252\n",
    "\n",
    "!uv pip install \"gemma[test] @ git+https://github.com/google-deepmind/gemma.git\"\n",
    "\n",
    "Also kauldron also has the same issue:\n",
    "\n",
    "!uv pip install --upgrade git+https://github.com/google-research/kauldron.git"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "attempted relative import with no known parent package",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mImportError\u001b[39m                               Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[5]\u001b[39m\u001b[32m, line 2\u001b[39m\n\u001b[32m      1\u001b[39m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mgemma\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m gm\n\u001b[32m----> \u001b[39m\u001b[32m2\u001b[39m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01m.\u001b[39;00m\u001b[34;01mautonotebook\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m tqdm \u001b[38;5;28;01mas\u001b[39;00m notebook_tqdm\n",
      "\u001b[31mImportError\u001b[39m: attempted relative import with no known parent package"
     ]
    }
   ],
   "source": [
    "from gemma import gm\n",
    "from .autonotebook import tqdm as notebook_tqdm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/ashly/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n",
      "2025-04-08 20:59:42.769976: W external/local_xla/xla/tsl/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with \"NOT_FOUND: Could not locate the credentials file.\". Retrieving token from GCE failed with \"FAILED_PRECONDITION: Error executing an HTTP request: libcurl code 6 meaning 'Could not resolve hostname', error details: Could not resolve host: metadata.google.internal\".\n",
      "E0408 20:59:57.347444 11565604 google_auth_provider.cc:188] Could not find the credentials file in the standard gcloud location [/Users/ashly/.config/gcloud/application_default_credentials.json]. You may specify a credentials file using $GOOGLE_APPLICATION_CREDENTIALS, or to use Google application default credentials, run: gcloud auth application-default login\n",
      "WARNING:absl:[process=0][thread=MainThread] No metadata found for any process_index, checkpoint_dir=gs://gemma-data/checkpoints/gemma3-1b-it. time elapsed=7.521667957305908 seconds. If the checkpoint does not contain jax.Array then it is expected. If checkpoint contains jax.Array then it should lead to an error eventually; if no error is raised then it is a bug.\n"
     ]
    },
    {
     "ename": "Exception",
     "evalue": "Encountered error while reading array index: (slice(0, 262144, 1), slice(0, 1152, 1)). See full TensorStore details: <bound method PyCapsule.spec of TensorStore({\n  'base': {\n    'driver': 'zarr',\n    'dtype': 'bfloat16',\n    'fill_missing_data_reads': False,\n    'kvstore': {\n      'base': {\n        'bucket': 'gemma-data',\n        'driver': 'gcs',\n        'path': 'checkpoints/gemma3-1b-it/',\n      },\n      'cache_pool': 'cache_pool#ocdbt',\n      'config': {\n        'compression': {'id': 'zstd'},\n        'max_decoded_node_bytes': 100000000,\n        'max_inline_value_bytes': 1024,\n        'uuid': 'd3b0160748c59779ee5c8b9a50591125',\n        'version_tree_arity_log2': 4,\n      },\n      'driver': 'ocdbt',\n      'experimental_read_coalescing_interval': '1ms',\n      'experimental_read_coalescing_merged_bytes': 500000000000,\n      'experimental_read_coalescing_threshold_bytes': 1000000,\n      'path': 'transformer/embedder.input_embedding/',\n    },\n    'metadata': {\n      'chunks': [262144, 1152],\n      'compressor': {'id': 'zstd', 'level': 1},\n      'dimension_separator': '.',\n      'dtype': 'bfloat16',\n      'fill_value': None,\n      'filters': None,\n      'order': 'C',\n      'shape': [262144, 1152],\n      'zarr_format': 2,\n    },\n    'recheck_cached_data': False,\n    'recheck_cached_metadata': False,\n  },\n  'context': {\n    'cache_pool': {},\n    'cache_pool#ocdbt': {'total_bytes_limit': 100000000},\n    'data_copy_concurrency': {},\n    'gcs_request_concurrency': {},\n    'gcs_request_retries': {},\n    'gcs_user_project': {},\n    'ocdbt_coordinator': {},\n  },\n  'driver': 'cast',\n  'dtype': 'bfloat16',\n  'transform': {\n    'input_exclusive_max': [[262144], [1152]],\n    'input_inclusive_min': [0, 0],\n  },\n})>.",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mKeyboardInterrupt\u001b[39m                         Traceback (most recent call last)",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/nest_asyncio.py:30\u001b[39m, in \u001b[36m_patch_asyncio.<locals>.run\u001b[39m\u001b[34m(main, debug)\u001b[39m\n\u001b[32m     29\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m---> \u001b[39m\u001b[32m30\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mloop\u001b[49m\u001b[43m.\u001b[49m\u001b[43mrun_until_complete\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtask\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m     31\u001b[39m \u001b[38;5;28;01mfinally\u001b[39;00m:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/nest_asyncio.py:92\u001b[39m, in \u001b[36m_patch_loop.<locals>.run_until_complete\u001b[39m\u001b[34m(self, future)\u001b[39m\n\u001b[32m     91\u001b[39m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m f.done():\n\u001b[32m---> \u001b[39m\u001b[32m92\u001b[39m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_run_once\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m     93\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m._stopping:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/nest_asyncio.py:115\u001b[39m, in \u001b[36m_patch_loop.<locals>._run_once\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    110\u001b[39m timeout = (\n\u001b[32m    111\u001b[39m     \u001b[32m0\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m ready \u001b[38;5;129;01mor\u001b[39;00m \u001b[38;5;28mself\u001b[39m._stopping\n\u001b[32m    112\u001b[39m     \u001b[38;5;28;01melse\u001b[39;00m \u001b[38;5;28mmin\u001b[39m(\u001b[38;5;28mmax\u001b[39m(\n\u001b[32m    113\u001b[39m         scheduled[\u001b[32m0\u001b[39m]._when - \u001b[38;5;28mself\u001b[39m.time(), \u001b[32m0\u001b[39m), \u001b[32m86400\u001b[39m) \u001b[38;5;28;01mif\u001b[39;00m scheduled\n\u001b[32m    114\u001b[39m     \u001b[38;5;28;01melse\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[32m--> \u001b[39m\u001b[32m115\u001b[39m event_list = \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_selector\u001b[49m\u001b[43m.\u001b[49m\u001b[43mselect\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    116\u001b[39m \u001b[38;5;28mself\u001b[39m._process_events(event_list)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/selectors.py:566\u001b[39m, in \u001b[36mKqueueSelector.select\u001b[39m\u001b[34m(self, timeout)\u001b[39m\n\u001b[32m    565\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m566\u001b[39m     kev_list = \u001b[38;5;28mself\u001b[39m._selector.control(\u001b[38;5;28;01mNone\u001b[39;00m, max_ev, timeout)\n\u001b[32m    567\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mInterruptedError\u001b[39;00m:\n",
      "\u001b[31mKeyboardInterrupt\u001b[39m: ",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[31mCancelledError\u001b[39m                            Traceback (most recent call last)",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/orbax/checkpoint/_src/serialization/serialization.py:441\u001b[39m, in \u001b[36m_read_array_index_and_device_put\u001b[39m\u001b[34m(devices, index, t, global_shape, new_shard_shape, dtype, byte_limiter, strict, dll, memory_kind)\u001b[39m\n\u001b[32m    440\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m441\u001b[39m   shard = \u001b[38;5;28;01mawait\u001b[39;00m _read_shard(\n\u001b[32m    442\u001b[39m       t=t,\n\u001b[32m    443\u001b[39m       new_shard_shape=new_shard_shape,\n\u001b[32m    444\u001b[39m       dtype=dtype,\n\u001b[32m    445\u001b[39m       requested_domain=requested_domain,\n\u001b[32m    446\u001b[39m       restricted_domain=restricted_domain,\n\u001b[32m    447\u001b[39m   )\n\u001b[32m    448\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mBaseException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/orbax/checkpoint/_src/serialization/serialization.py:383\u001b[39m, in \u001b[36m_read_shard\u001b[39m\u001b[34m(t, new_shard_shape, dtype, requested_domain, restricted_domain)\u001b[39m\n\u001b[32m    382\u001b[39m out = np.zeros(new_shard_shape, dtype=t.dtype.numpy_dtype)\n\u001b[32m--> \u001b[39m\u001b[32m383\u001b[39m \u001b[38;5;28;01mawait\u001b[39;00m ts.array(out)[ts.d[:].translate_to[requested_domain.origin]][\n\u001b[32m    384\u001b[39m     restricted_domain\n\u001b[32m    385\u001b[39m ].write(t[restricted_domain])\n\u001b[32m    386\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m dtype \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m    387\u001b[39m   \u001b[38;5;66;03m# Cast while reloading on process to avoid 2 copies on device if the\u001b[39;00m\n\u001b[32m    388\u001b[39m   \u001b[38;5;66;03m# casting is done on device.\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/asyncio/futures.py:287\u001b[39m, in \u001b[36mFuture.__await__\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    286\u001b[39m     \u001b[38;5;28mself\u001b[39m._asyncio_future_blocking = \u001b[38;5;28;01mTrue\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m287\u001b[39m     \u001b[38;5;28;01myield\u001b[39;00m \u001b[38;5;28mself\u001b[39m  \u001b[38;5;66;03m# This tells Task to wait for completion.\u001b[39;00m\n\u001b[32m    288\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m.done():\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/asyncio/tasks.py:349\u001b[39m, in \u001b[36mTask.__wakeup\u001b[39m\u001b[34m(self, future)\u001b[39m\n\u001b[32m    348\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m349\u001b[39m     \u001b[43mfuture\u001b[49m\u001b[43m.\u001b[49m\u001b[43mresult\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    350\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mBaseException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m exc:\n\u001b[32m    351\u001b[39m     \u001b[38;5;66;03m# This may also be a cancellation.\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/asyncio/futures.py:198\u001b[39m, in \u001b[36mFuture.result\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    197\u001b[39m     exc = \u001b[38;5;28mself\u001b[39m._make_cancelled_error()\n\u001b[32m--> \u001b[39m\u001b[32m198\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m exc\n\u001b[32m    199\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m._state != _FINISHED:\n",
      "\u001b[31mCancelledError\u001b[39m: ",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[31mException\u001b[39m                                 Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[3]\u001b[39m\u001b[32m, line 2\u001b[39m\n\u001b[32m      1\u001b[39m model = gm.nn.Gemma3_1B() \u001b[38;5;66;03m# rasied issue on this  https://github.com/google/grain/issues/803\u001b[39;00m\n\u001b[32m----> \u001b[39m\u001b[32m2\u001b[39m params = \u001b[43mgm\u001b[49m\u001b[43m.\u001b[49m\u001b[43mckpts\u001b[49m\u001b[43m.\u001b[49m\u001b[43mload_params\u001b[49m\u001b[43m(\u001b[49m\u001b[43mgm\u001b[49m\u001b[43m.\u001b[49m\u001b[43mckpts\u001b[49m\u001b[43m.\u001b[49m\u001b[43mCheckpointPath\u001b[49m\u001b[43m.\u001b[49m\u001b[43mGEMMA3_1B_IT\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/gemma/gm/ckpts/_checkpoint.py:250\u001b[39m, in \u001b[36mload_params\u001b[39m\u001b[34m(path, params, donate, text_only, sharding, quantize)\u001b[39m\n\u001b[32m    248\u001b[39m output_with_skip = metadata.make_tree_for_params(params)\n\u001b[32m    249\u001b[39m restore_fn = functools.partial(ckpt.restore, path)\n\u001b[32m--> \u001b[39m\u001b[32m250\u001b[39m output = \u001b[43m_partial_restore\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrestore_fn\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43moutput_with_skip\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    252\u001b[39m \u001b[38;5;66;03m# TODO(epot): Better API. Currently this do not quantize the weights, but\u001b[39;00m\n\u001b[32m    253\u001b[39m \u001b[38;5;66;03m# just refactor the params to the QAT structure.\u001b[39;00m\n\u001b[32m    254\u001b[39m \u001b[38;5;66;03m# Eventually quantize the params. Note: It would be better to do this\u001b[39;00m\n\u001b[32m    255\u001b[39m \u001b[38;5;66;03m# while the weights are loaded, so restore do not use unecessary memory.\u001b[39;00m\n\u001b[32m    256\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m quantize:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/gemma/gm/ckpts/_checkpoint.py:399\u001b[39m, in \u001b[36m_partial_restore\u001b[39m\u001b[34m(restore_fn, tree_with_skip)\u001b[39m\n\u001b[32m    397\u001b[39m \u001b[38;5;66;03m# TODO(epot): Implement once orbax supports partial restore.\u001b[39;00m\n\u001b[32m    398\u001b[39m tree = _unwrap_skip(tree_with_skip)\n\u001b[32m--> \u001b[39m\u001b[32m399\u001b[39m tree = \u001b[43mrestore_fn\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtree\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    400\u001b[39m _release_skip(tree, tree_with_skip)\n\u001b[32m    401\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m tree\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/orbax/checkpoint/_src/checkpointers/standard_checkpointer.py:152\u001b[39m, in \u001b[36mStandardCheckpointer.restore\u001b[39m\u001b[34m(self, directory, target, strict)\u001b[39m\n\u001b[32m    125\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mrestore\u001b[39m(\n\u001b[32m    126\u001b[39m     \u001b[38;5;28mself\u001b[39m,\n\u001b[32m    127\u001b[39m     directory: epath.PathLike,\n\u001b[32m   (...)\u001b[39m\u001b[32m    130\u001b[39m     strict: \u001b[38;5;28mbool\u001b[39m = \u001b[38;5;28;01mTrue\u001b[39;00m,\n\u001b[32m    131\u001b[39m ) -> Any:\n\u001b[32m    132\u001b[39m \u001b[38;5;250m  \u001b[39m\u001b[33;03m\"\"\"Restores a checkpoint.\u001b[39;00m\n\u001b[32m    133\u001b[39m \n\u001b[32m    134\u001b[39m \u001b[33;03m  Args:\u001b[39;00m\n\u001b[32m   (...)\u001b[39m\u001b[32m    150\u001b[39m \u001b[33;03m    The restored checkpoint.\u001b[39;00m\n\u001b[32m    151\u001b[39m \u001b[33;03m  \"\"\"\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m152\u001b[39m   \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43msuper\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m.\u001b[49m\u001b[43mrestore\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    153\u001b[39m \u001b[43m      \u001b[49m\u001b[43mdirectory\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43margs\u001b[49m\u001b[43m=\u001b[49m\u001b[43mStandardRestore\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtarget\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mstrict\u001b[49m\u001b[43m=\u001b[49m\u001b[43mstrict\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    154\u001b[39m \u001b[43m  \u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/orbax/checkpoint/_src/checkpointers/async_checkpointer.py:552\u001b[39m, in \u001b[36mAsyncCheckpointer.restore\u001b[39m\u001b[34m(self, directory, *args, **kwargs)\u001b[39m\n\u001b[32m    550\u001b[39m \u001b[38;5;250m\u001b[39m\u001b[33;03m\"\"\"See superclass documentation.\"\"\"\u001b[39;00m\n\u001b[32m    551\u001b[39m \u001b[38;5;28mself\u001b[39m.wait_until_finished()\n\u001b[32m--> \u001b[39m\u001b[32m552\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43msuper\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m.\u001b[49m\u001b[43mrestore\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdirectory\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/orbax/checkpoint/_src/checkpointers/checkpointer.py:295\u001b[39m, in \u001b[36mCheckpointer.restore\u001b[39m\u001b[34m(self, directory, *args, **kwargs)\u001b[39m\n\u001b[32m    293\u001b[39m logging.info(\u001b[33m'\u001b[39m\u001b[33mRestoring checkpoint from \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[33m.\u001b[39m\u001b[33m'\u001b[39m, directory)\n\u001b[32m    294\u001b[39m ckpt_args = construct_checkpoint_args(\u001b[38;5;28mself\u001b[39m._handler, \u001b[38;5;28;01mFalse\u001b[39;00m, *args, **kwargs)\n\u001b[32m--> \u001b[39m\u001b[32m295\u001b[39m restored = \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_restore\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdirectory\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43margs\u001b[49m\u001b[43m=\u001b[49m\u001b[43mckpt_args\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    296\u001b[39m multihost.sync_global_processes(\n\u001b[32m    297\u001b[39m     multihost.unique_barrier_key(\n\u001b[32m    298\u001b[39m         \u001b[33m'\u001b[39m\u001b[33mCheckpointer:restore\u001b[39m\u001b[33m'\u001b[39m,\n\u001b[32m   (...)\u001b[39m\u001b[32m    301\u001b[39m     processes=\u001b[38;5;28mself\u001b[39m._active_processes,\n\u001b[32m    302\u001b[39m )\n\u001b[32m    303\u001b[39m restore_duration_secs = time.time() - restore_start_time\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/orbax/checkpoint/_src/checkpointers/checkpointer.py:314\u001b[39m, in \u001b[36mCheckpointer._restore\u001b[39m\u001b[34m(self, directory, args)\u001b[39m\n\u001b[32m    311\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m_restore\u001b[39m(\n\u001b[32m    312\u001b[39m     \u001b[38;5;28mself\u001b[39m, directory: epath.PathLike, args: checkpoint_args.CheckpointArgs\n\u001b[32m    313\u001b[39m ) -> Any:\n\u001b[32m--> \u001b[39m\u001b[32m314\u001b[39m   \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_handler\u001b[49m\u001b[43m.\u001b[49m\u001b[43mrestore\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdirectory\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43margs\u001b[49m\u001b[43m=\u001b[49m\u001b[43margs\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/orbax/checkpoint/_src/handlers/standard_checkpoint_handler.py:246\u001b[39m, in \u001b[36mStandardCheckpointHandler.restore\u001b[39m\u001b[34m(self, directory, item, args)\u001b[39m\n\u001b[32m    244\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m args.strict:\n\u001b[32m    245\u001b[39m   restore_args = jax.tree.map(_replace_strict, restore_args)\n\u001b[32m--> \u001b[39m\u001b[32m246\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_impl\u001b[49m\u001b[43m.\u001b[49m\u001b[43mrestore\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    247\u001b[39m \u001b[43m    \u001b[49m\u001b[43mdirectory\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    248\u001b[39m \u001b[43m    \u001b[49m\u001b[43margs\u001b[49m\u001b[43m=\u001b[49m\u001b[43mpytree_checkpoint_handler\u001b[49m\u001b[43m.\u001b[49m\u001b[43mPyTreeRestoreArgs\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    249\u001b[39m \u001b[43m        \u001b[49m\u001b[43mitem\u001b[49m\u001b[43m=\u001b[49m\u001b[43margs\u001b[49m\u001b[43m.\u001b[49m\u001b[43mitem\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mrestore_args\u001b[49m\u001b[43m=\u001b[49m\u001b[43mrestore_args\u001b[49m\n\u001b[32m    250\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    251\u001b[39m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/orbax/checkpoint/_src/handlers/pytree_checkpoint_handler.py:796\u001b[39m, in \u001b[36mPyTreeCheckpointHandler.restore\u001b[39m\u001b[34m(self, directory, item, restore_args, transforms, transforms_default_to_original, legacy_transform_fn, args)\u001b[39m\n\u001b[32m    786\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m (\n\u001b[32m    787\u001b[39m     (directory / PYTREE_METADATA_FILE).exists()\n\u001b[32m    788\u001b[39m     \u001b[38;5;129;01mand\u001b[39;00m can_ignore_aggregate_file\n\u001b[32m    789\u001b[39m     \u001b[38;5;129;01mand\u001b[39;00m transforms \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[32m    790\u001b[39m     \u001b[38;5;129;01mand\u001b[39;00m legacy_transform_fn \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[32m    791\u001b[39m ):\n\u001b[32m    792\u001b[39m   args = BasePyTreeRestoreArgs(\n\u001b[32m    793\u001b[39m       item,\n\u001b[32m    794\u001b[39m       restore_args=restore_args,\n\u001b[32m    795\u001b[39m   )\n\u001b[32m--> \u001b[39m\u001b[32m796\u001b[39m   \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_handler_impl\u001b[49m\u001b[43m.\u001b[49m\u001b[43mrestore\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdirectory\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43margs\u001b[49m\u001b[43m=\u001b[49m\u001b[43margs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    798\u001b[39m logging.vlog(\u001b[32m1\u001b[39m, \u001b[33m'\u001b[39m\u001b[33mdirectory=\u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[33m, restore_args=\u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[33m'\u001b[39m, directory, restore_args)\n\u001b[32m    799\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m directory.exists():\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/orbax/checkpoint/_src/handlers/base_pytree_checkpoint_handler.py:760\u001b[39m, in \u001b[36mBasePyTreeCheckpointHandler.restore\u001b[39m\u001b[34m(self, directory, args)\u001b[39m\n\u001b[32m    752\u001b[39m param_infos = \u001b[38;5;28mself\u001b[39m._get_param_infos(\n\u001b[32m    753\u001b[39m     item=value_metadata_tree,\n\u001b[32m    754\u001b[39m     directory=directory,\n\u001b[32m   (...)\u001b[39m\u001b[32m    757\u001b[39m     raise_array_data_missing_error=raise_array_data_missing_error,\n\u001b[32m    758\u001b[39m )\n\u001b[32m    759\u001b[39m \u001b[38;5;66;03m# Begin restore.\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m760\u001b[39m tree_memory_size, restored_item = \u001b[43masyncio_utils\u001b[49m\u001b[43m.\u001b[49m\u001b[43mrun_sync\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    761\u001b[39m \u001b[43m    \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_maybe_deserialize\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    762\u001b[39m \u001b[43m        \u001b[49m\u001b[43mitem\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mvalue_metadata_tree\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mparam_infos\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mrestore_args\u001b[49m\n\u001b[32m    763\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    764\u001b[39m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    766\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m logging.vlog_is_on(\u001b[32m1\u001b[39m):\n\u001b[32m    767\u001b[39m   logging.vlog(\u001b[32m1\u001b[39m, \u001b[33m'\u001b[39m\u001b[33mparam_infos: \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[33m'\u001b[39m, param_infos)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/orbax/checkpoint/_src/asyncio_utils.py:50\u001b[39m, in \u001b[36mrun_sync\u001b[39m\u001b[34m(coro, enable_nest_asyncio)\u001b[39m\n\u001b[32m     48\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m:\n\u001b[32m     49\u001b[39m   \u001b[38;5;28;01mpass\u001b[39;00m\n\u001b[32m---> \u001b[39m\u001b[32m50\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43masyncio\u001b[49m\u001b[43m.\u001b[49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[43mcoro\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/nest_asyncio.py:35\u001b[39m, in \u001b[36m_patch_asyncio.<locals>.run\u001b[39m\u001b[34m(main, debug)\u001b[39m\n\u001b[32m     33\u001b[39m task.cancel()\n\u001b[32m     34\u001b[39m \u001b[38;5;28;01mwith\u001b[39;00m suppress(asyncio.CancelledError):\n\u001b[32m---> \u001b[39m\u001b[32m35\u001b[39m     \u001b[43mloop\u001b[49m\u001b[43m.\u001b[49m\u001b[43mrun_until_complete\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtask\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/nest_asyncio.py:98\u001b[39m, in \u001b[36m_patch_loop.<locals>.run_until_complete\u001b[39m\u001b[34m(self, future)\u001b[39m\n\u001b[32m     95\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m f.done():\n\u001b[32m     96\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m(\n\u001b[32m     97\u001b[39m         \u001b[33m'\u001b[39m\u001b[33mEvent loop stopped before Future completed.\u001b[39m\u001b[33m'\u001b[39m)\n\u001b[32m---> \u001b[39m\u001b[32m98\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mf\u001b[49m\u001b[43m.\u001b[49m\u001b[43mresult\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/asyncio/futures.py:203\u001b[39m, in \u001b[36mFuture.result\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    201\u001b[39m \u001b[38;5;28mself\u001b[39m.__log_traceback = \u001b[38;5;28;01mFalse\u001b[39;00m\n\u001b[32m    202\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m._exception \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m203\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;28mself\u001b[39m._exception.with_traceback(\u001b[38;5;28mself\u001b[39m._exception_tb)\n\u001b[32m    204\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m._result\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/asyncio/tasks.py:279\u001b[39m, in \u001b[36mTask.__step\u001b[39m\u001b[34m(***failed resolving arguments***)\u001b[39m\n\u001b[32m    277\u001b[39m         result = coro.send(\u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[32m    278\u001b[39m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m279\u001b[39m         result = coro.throw(exc)\n\u001b[32m    280\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mStopIteration\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m exc:\n\u001b[32m    281\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m._must_cancel:\n\u001b[32m    282\u001b[39m         \u001b[38;5;66;03m# Task is cancelled right before coro stops.\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/orbax/checkpoint/_src/handlers/base_pytree_checkpoint_handler.py:584\u001b[39m, in \u001b[36mBasePyTreeCheckpointHandler._maybe_deserialize\u001b[39m\u001b[34m(self, item, metadata, param_infos, restore_args)\u001b[39m\n\u001b[32m    580\u001b[39m \u001b[38;5;28;01mfor\u001b[39;00m request \u001b[38;5;129;01min\u001b[39;00m batch_requests:\n\u001b[32m    581\u001b[39m   deserialized_batches_ops.append(\n\u001b[32m    582\u001b[39m       request.handler.deserialize(request.infos, request.args)\n\u001b[32m    583\u001b[39m   )\n\u001b[32m--> \u001b[39m\u001b[32m584\u001b[39m deserialized_batches += \u001b[38;5;28;01mawait\u001b[39;00m asyncio.gather(*deserialized_batches_ops)\n\u001b[32m    586\u001b[39m tree_memory_size = \u001b[32m0\u001b[39m\n\u001b[32m    587\u001b[39m flat_restored = {}\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/asyncio/tasks.py:349\u001b[39m, in \u001b[36mTask.__wakeup\u001b[39m\u001b[34m(self, future)\u001b[39m\n\u001b[32m    347\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m__wakeup\u001b[39m(\u001b[38;5;28mself\u001b[39m, future):\n\u001b[32m    348\u001b[39m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m349\u001b[39m         \u001b[43mfuture\u001b[49m\u001b[43m.\u001b[49m\u001b[43mresult\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    350\u001b[39m     \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mBaseException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m exc:\n\u001b[32m    351\u001b[39m         \u001b[38;5;66;03m# This may also be a cancellation.\u001b[39;00m\n\u001b[32m    352\u001b[39m         \u001b[38;5;28mself\u001b[39m.__step(exc)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/asyncio/tasks.py:279\u001b[39m, in \u001b[36mTask.__step\u001b[39m\u001b[34m(***failed resolving arguments***)\u001b[39m\n\u001b[32m    277\u001b[39m         result = coro.send(\u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[32m    278\u001b[39m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m279\u001b[39m         result = coro.throw(exc)\n\u001b[32m    280\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mStopIteration\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m exc:\n\u001b[32m    281\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m._must_cancel:\n\u001b[32m    282\u001b[39m         \u001b[38;5;66;03m# Task is cancelled right before coro stops.\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/orbax/checkpoint/_src/serialization/type_handlers.py:1315\u001b[39m, in \u001b[36mArrayHandler.deserialize\u001b[39m\u001b[34m(self, infos, args)\u001b[39m\n\u001b[32m   1309\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m._array_metadata_store \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m   1310\u001b[39m   deserialize_ops.append(\n\u001b[32m   1311\u001b[39m       \u001b[38;5;28mself\u001b[39m._array_metadata_store.read(\n\u001b[32m   1312\u001b[39m           checkpoint_dir=infos[\u001b[32m0\u001b[39m].parent_dir,\n\u001b[32m   1313\u001b[39m       )\n\u001b[32m   1314\u001b[39m   )\n\u001b[32m-> \u001b[39m\u001b[32m1315\u001b[39m   *ret, array_metadatas = \u001b[38;5;28;01mawait\u001b[39;00m asyncio.gather(*deserialize_ops)\n\u001b[32m   1317\u001b[39m   \u001b[38;5;28;01mif\u001b[39;00m array_metadatas:\n\u001b[32m   1318\u001b[39m     ret = \u001b[38;5;28mself\u001b[39m._parse_array_metadatas(array_metadatas, infos, ret)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/asyncio/tasks.py:349\u001b[39m, in \u001b[36mTask.__wakeup\u001b[39m\u001b[34m(self, future)\u001b[39m\n\u001b[32m    347\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m__wakeup\u001b[39m(\u001b[38;5;28mself\u001b[39m, future):\n\u001b[32m    348\u001b[39m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m349\u001b[39m         \u001b[43mfuture\u001b[49m\u001b[43m.\u001b[49m\u001b[43mresult\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    350\u001b[39m     \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mBaseException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m exc:\n\u001b[32m    351\u001b[39m         \u001b[38;5;66;03m# This may also be a cancellation.\u001b[39;00m\n\u001b[32m    352\u001b[39m         \u001b[38;5;28mself\u001b[39m.__step(exc)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/asyncio/tasks.py:279\u001b[39m, in \u001b[36mTask.__step\u001b[39m\u001b[34m(***failed resolving arguments***)\u001b[39m\n\u001b[32m    277\u001b[39m         result = coro.send(\u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[32m    278\u001b[39m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m279\u001b[39m         result = coro.throw(exc)\n\u001b[32m    280\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mStopIteration\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m exc:\n\u001b[32m    281\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m._must_cancel:\n\u001b[32m    282\u001b[39m         \u001b[38;5;66;03m# Task is cancelled right before coro stops.\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/orbax/checkpoint/_src/serialization/serialization.py:544\u001b[39m, in \u001b[36masync_deserialize\u001b[39m\u001b[34m(user_sharding, tensorstore_spec, global_shape, dtype, byte_limiter, context, assume_metadata, strict)\u001b[39m\n\u001b[32m    542\u001b[39m global_shape = \u001b[38;5;28mtuple\u001b[39m(t.shape \u001b[38;5;28;01mif\u001b[39;00m global_shape \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;28;01melse\u001b[39;00m global_shape)\n\u001b[32m    543\u001b[39m new_shard_shape = sharding.shard_shape(global_shape)\n\u001b[32m--> \u001b[39m\u001b[32m544\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m read_and_create_array(\n\u001b[32m    545\u001b[39m     t,\n\u001b[32m    546\u001b[39m     global_shape=global_shape,\n\u001b[32m    547\u001b[39m     new_shard_shape=new_shard_shape,\n\u001b[32m    548\u001b[39m     sharding=sharding,\n\u001b[32m    549\u001b[39m     dtype=dtype,\n\u001b[32m    550\u001b[39m     byte_limiter=byte_limiter,\n\u001b[32m    551\u001b[39m     strict=strict,\n\u001b[32m    552\u001b[39m     dll=dll,\n\u001b[32m    553\u001b[39m )\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/orbax/checkpoint/_src/serialization/serialization.py:503\u001b[39m, in \u001b[36mread_and_create_array\u001b[39m\u001b[34m(t, global_shape, new_shard_shape, sharding, dtype, byte_limiter, strict, dll)\u001b[39m\n\u001b[32m    484\u001b[39m     local_indices_devices_map[\n\u001b[32m    485\u001b[39m         np_utils.to_hashable_index(idx, shape=global_shape)\n\u001b[32m    486\u001b[39m     ].append(d)\n\u001b[32m    488\u001b[39m read_array_coros = [\n\u001b[32m    489\u001b[39m     _read_array_index_and_device_put(\n\u001b[32m    490\u001b[39m         devices,\n\u001b[32m   (...)\u001b[39m\u001b[32m    501\u001b[39m     \u001b[38;5;28;01mfor\u001b[39;00m idx, devices \u001b[38;5;129;01min\u001b[39;00m local_indices_devices_map.items()\n\u001b[32m    502\u001b[39m ]\n\u001b[32m--> \u001b[39m\u001b[32m503\u001b[39m dbs = \u001b[38;5;28msum\u001b[39m(\u001b[38;5;28;01mawait\u001b[39;00m asyncio.gather(*read_array_coros), [])\n\u001b[32m    504\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m jax.make_array_from_single_device_arrays(global_shape, sharding, dbs)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/asyncio/tasks.py:349\u001b[39m, in \u001b[36mTask.__wakeup\u001b[39m\u001b[34m(self, future)\u001b[39m\n\u001b[32m    347\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m__wakeup\u001b[39m(\u001b[38;5;28mself\u001b[39m, future):\n\u001b[32m    348\u001b[39m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m349\u001b[39m         \u001b[43mfuture\u001b[49m\u001b[43m.\u001b[49m\u001b[43mresult\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    350\u001b[39m     \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mBaseException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m exc:\n\u001b[32m    351\u001b[39m         \u001b[38;5;66;03m# This may also be a cancellation.\u001b[39;00m\n\u001b[32m    352\u001b[39m         \u001b[38;5;28mself\u001b[39m.__step(exc)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/asyncio/tasks.py:279\u001b[39m, in \u001b[36mTask.__step\u001b[39m\u001b[34m(***failed resolving arguments***)\u001b[39m\n\u001b[32m    277\u001b[39m         result = coro.send(\u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[32m    278\u001b[39m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m279\u001b[39m         result = coro.throw(exc)\n\u001b[32m    280\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mStopIteration\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m exc:\n\u001b[32m    281\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m._must_cancel:\n\u001b[32m    282\u001b[39m         \u001b[38;5;66;03m# Task is cancelled right before coro stops.\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/MahindraWork/gemmaft/gemmatest/lib/python3.11/site-packages/orbax/checkpoint/_src/serialization/serialization.py:449\u001b[39m, in \u001b[36m_read_array_index_and_device_put\u001b[39m\u001b[34m(devices, index, t, global_shape, new_shard_shape, dtype, byte_limiter, strict, dll, memory_kind)\u001b[39m\n\u001b[32m    441\u001b[39m   shard = \u001b[38;5;28;01mawait\u001b[39;00m _read_shard(\n\u001b[32m    442\u001b[39m       t=t,\n\u001b[32m    443\u001b[39m       new_shard_shape=new_shard_shape,\n\u001b[32m   (...)\u001b[39m\u001b[32m    446\u001b[39m       restricted_domain=restricted_domain,\n\u001b[32m    447\u001b[39m   )\n\u001b[32m    448\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mBaseException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[32m--> \u001b[39m\u001b[32m449\u001b[39m   \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m(  \u001b[38;5;66;03m# pylint: disable=broad-exception-raised\u001b[39;00m\n\u001b[32m    450\u001b[39m       \u001b[33mf\u001b[39m\u001b[33m'\u001b[39m\u001b[33mEncountered error while reading array index: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mindex\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m. See full\u001b[39m\u001b[33m'\u001b[39m\n\u001b[32m    451\u001b[39m       \u001b[33mf\u001b[39m\u001b[33m'\u001b[39m\u001b[33m TensorStore details: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mt.spec\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m.\u001b[39m\u001b[33m'\u001b[39m\n\u001b[32m    452\u001b[39m   ) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01me\u001b[39;00m\n\u001b[32m    453\u001b[39m \u001b[38;5;28;01mfor\u001b[39;00m device \u001b[38;5;129;01min\u001b[39;00m devices:\n\u001b[32m    454\u001b[39m   sharding = jax.sharding.SingleDeviceSharding(\n\u001b[32m    455\u001b[39m       device, memory_kind=memory_kind\n\u001b[32m    456\u001b[39m   )\n",
      "\u001b[31mException\u001b[39m: Encountered error while reading array index: (slice(0, 262144, 1), slice(0, 1152, 1)). See full TensorStore details: <bound method PyCapsule.spec of TensorStore({\n  'base': {\n    'driver': 'zarr',\n    'dtype': 'bfloat16',\n    'fill_missing_data_reads': False,\n    'kvstore': {\n      'base': {\n        'bucket': 'gemma-data',\n        'driver': 'gcs',\n        'path': 'checkpoints/gemma3-1b-it/',\n      },\n      'cache_pool': 'cache_pool#ocdbt',\n      'config': {\n        'compression': {'id': 'zstd'},\n        'max_decoded_node_bytes': 100000000,\n        'max_inline_value_bytes': 1024,\n        'uuid': 'd3b0160748c59779ee5c8b9a50591125',\n        'version_tree_arity_log2': 4,\n      },\n      'driver': 'ocdbt',\n      'experimental_read_coalescing_interval': '1ms',\n      'experimental_read_coalescing_merged_bytes': 500000000000,\n      'experimental_read_coalescing_threshold_bytes': 1000000,\n      'path': 'transformer/embedder.input_embedding/',\n    },\n    'metadata': {\n      'chunks': [262144, 1152],\n      'compressor': {'id': 'zstd', 'level': 1},\n      'dimension_separator': '.',\n      'dtype': 'bfloat16',\n      'fill_value': None,\n      'filters': None,\n      'order': 'C',\n      'shape': [262144, 1152],\n      'zarr_format': 2,\n    },\n    'recheck_cached_data': False,\n    'recheck_cached_metadata': False,\n  },\n  'context': {\n    'cache_pool': {},\n    'cache_pool#ocdbt': {'total_bytes_limit': 100000000},\n    'data_copy_concurrency': {},\n    'gcs_request_concurrency': {},\n    'gcs_request_retries': {},\n    'gcs_user_project': {},\n    'ocdbt_coordinator': {},\n  },\n  'driver': 'cast',\n  'dtype': 'bfloat16',\n  'transform': {\n    'input_exclusive_max': [[262144], [1152]],\n    'input_inclusive_min': [0, 0],\n  },\n})>."
     ]
    }
   ],
   "source": [
    "model = gm.nn.Gemma3_1B() # rasied issue on this  https://github.com/google/grain/issues/803\n",
    "params = gm.ckpts.load_params(gm.ckpts.CheckpointPath.GEMMA3_1B_IT)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "gemmatest",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
